### PR TITLE
Merge Simplistic_Memes contributions

### LINKED ISSUE #35: Merge Simplistic_Memes contributions
Title.

### PR DESCRIPTION
**Pull request by simplistic6502**
Implements feature additions and bugfixes from Simplistic-Memes/smb into the main repro. This commit resolves #35

### CODE REVIEW

**Comment by threecreepio** [comment]
With the input display, maybe it would work better to store which inputs to draw in `UpdateStatusInput`, and then do the drawing in NMI? I feel like if using the VRAM buffer it won't be accurate enough to be relied on, since you won't be able to count on it actually matching your inputs. Maybe if it could fit into 3-4 characters (say, LR/UD/B/A) or something it would be fast enough to not break rendering? Not sure..

**Comment by Simplistic-Memes** [comment]
You bring up a very fair point, I failed to consider the unreliability of writing to VRAM_Buffer1, especially when only one of the two VRAM buffers can be emptied on any given frame. I'll try to remedy that issue within the next couple of days; thanks for pointing that out! Might have not have to reallocate the VRAM buffer in that event.

**Comment by Simplistic-Memes** [comment]
Updated the Simplistic-Memes/smb:features branch to include all the commits that have been made since I created that branch. Apologies for closing this pull request temporarily, I'm relatively unfamiliar with GitHub's architecture and didn't realize I did that. Still looking into how I could write player inputs in NMI, thinking I'll have to use WRAM to store the previous frame's inputs but I haven't dabbled with rearranging WRAM nor writing to the PPU without the VRAM buffer, but I hope the current implementation of the input display is satisfactory for the time being.

**Comment by threecreepio** [comment]
image
What is the "HUD" option supposed to do? Right now it seems to just stop updating the framerule, frame and 'x' values. Not quite sure I get it. :)

**Comment by Simplistic-Memes** [comment]
The intended function of the “HUD” option is to disable those values from updating if desired. One feature that top-level speedrunners had been wanting to be implemented into the practice ROM is the ability to toggle those values off for more effective speedrun practice. For example, disabling the frame counter is particularly useful for practicing TAS 8-2 bullet bill glitch, as an over-reliance on looking at the frame counter can form bad habits for performing the trick in runs; some people don’t practice tricks like TAS 8-2 in the SMB practice hack for this reason. I can definitely see why the intention of this option is confusing; “HUD” is supposed to refer to the “heads-up display”, but some people call this area of the screen the “status bar” instead. In the features branch of my fork, I’ve changed the option name to “INFO” to hopefully remove some confusion.

**Comment by Simplistic-Memes** [comment]
Going to go ahead and merge, given permission from pellsson. Let me know if anything is broken or needs to be changed.

**Comment by sciolist** [comment]
Ah gotcha, cool!

**Pull request merged**
